# Generated by Django 4.0.4 on 2022-07-20 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.TextField(max_length=5, primary_key=True, serialize=False, verbose_name='HID')),
                ('name', models.TextField(max_length=120, verbose_name='HOTEL')),
                ('price', models.IntegerField(max_length=12, verbose_name='PRICE_RUPEES')),
                ('Number_of_reviews', models.TextField(max_length=125, verbose_name='NUMBER_OF_REVIEWS')),
                ('Lat', models.IntegerField(max_length=20, verbose_name='Lat')),
                ('Lng', models.IntegerField(max_length=20, verbose_name='Lng')),
                ('Hote_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='id')),
                ('POIS', models.TextField(max_length=255, verbose_name='POIs')),
                ('PRIORITY_1', models.TextField(max_length=255, verbose_name='PRIORITY_1')),
                ('PRIORITY_2', models.TextField(max_length=255, verbose_name='PRIORITY_2')),
                ('PRIORITY_3', models.TextField(max_length=255, verbose_name='PRIORITY_3')),
                ('PRIORITY_4', models.TextField(max_length=255, verbose_name='PRIORITY_4')),
                ('PRIORITY_5', models.TextField(max_length=255, verbose_name='PRIORITY_5')),
                ('PLACE_LOGO', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_person', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=12)),
                ('date_in', models.DateField(max_length=12)),
                ('date_out', models.DateField(max_length=12)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.hotel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
