# Generated by Django 4.0.4 on 2022-07-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.TextField(max_length=5, primary_key=True, serialize=False, verbose_name='hotel_id'),
        ),
    ]
