# Generated by Django 4.0.4 on 2022-07-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_alter_hotel_hotel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel_id',
        ),
    ]
