# Generated by Django 4.0.4 on 2022-07-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_remove_booking_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journey.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_in',
            field=models.DateField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_out',
            field=models.DateField(blank=True, max_length=12, null=True),
        ),
    ]
